import pandas as pd
import matplotlib.pyplot as plt
results = pd.read_csv("population_heterozygosity_results.csv")
location_ho = results.groupby("Location")["Ho"].mean()
plt.figure(figsize=(8, 5))
plt.bar(location_ho.index, location_ho.values)
plt.title("Average Observed Hetrozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Average Ho")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Average_observed_heterozygosity.png", dpi=300)
plt.show()
location_he = results.groupby("Location")["He"].mean()
plt.figure(figsize=(8, 5))
plt.bar(location_he.index, location_he.values)
plt.title("Average Expected Heterozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Average He")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Average_expected_heterozygosity.png", dpi=300)
plt.show()
comparison = results.groupby("Location")[["Ho", "He"]].mean()
comparison.plot(kind="bar", figsize=(8, 5))
plt.title("Observed vs Expected Heterozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Heterozygosity")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("observed_vs_expected_heterozygosity.png", dpi=300)
plt.show()
marker_ho = results.groupby("Marker")["Ho"].mean()
plt.figure(figsize=(10, 5))
plt.bar(marker_ho.index, marker_ho.values)
plt.title("Average Observed Hetrozygosity by Marker")
plt.xlabel("Microsatellite Marker")
plt.ylabel("Average Ho")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("marker_heterozygosity.png", dpi=300)
plt.show()
import seaborn as sns
# Heatmap of observed heterozygosity by location and marker
heatmap_data = results.pivot_table(index="Location", columns="Marker", values="Ho")
plt.figure(figsize=(12, 8))
sns.heatmap(heatmap_data,annot=True, fmt=".2f", cmap="viridis")
plt.title("Observed Heterozygosity (Ho) across Locations and Markers")
plt.xlabel("Microsatellite Marker")
plt.ylabel("Location")
plt.tight_layout()
plt.savefig("Ho_heatmap.png", dpi=300)
plt.show()
# Scatter plot of observed vs expected heterozygosity
plt.figure(figsize=(9, 7))
plt.scatter(results["Ho"], results["He"], alpha=0.7)
min_value = min(results["Ho"].min(), results["He"].min())
max_value = max(results["Ho"].max(), results["He"].max())
plt.plot([min_value, max_value], [min_value, max_value], linestyle="--")
plt.xlabel("Obsereved Heterozygosity (Ho)")
plt.ylabel("Expected heterozygosity (He)")
plt.title("Observed vs Expected Heterozygosity")
plt.tight_layout()
plt.savefig("Ho_vs_He_scatter.png", dpi=300)
plt.show()
# Average Ho and He by location
population_summary = results.groupby("Location")[["Ho", "He"]].mean()
population_summary.plot(kind="bar", figsize=(12, 7))
plt.xlabel("Location")
plt.ylabel("Mean Heterozygosity")
plt.title("Mean Observed and Expected Heterozygosity by Location")
plt.xticks(rotation=45, ha="right")
plt.legend(["Ho", "He"])
plt.tight_layout()
plt.savefig("Mean_Ho_by_location.png", dpi=300)
plt.show()
# Average Ho and He by microsatellite marker
marker_summary = results.groupby("Marker")[["Ho", "He"]].mean()
marker_summary.plot(kind="bar", figsize=(11, 7))
plt.xlabel("Microsatellite Marker")
plt.ylabel("Mean Heterozygosity")
plt.title("Mean Observed and Expected Heterozygosity by Marker")
plt.xticks(rotation=45)
plt.legend(["Ho", "He"])
plt.tight_layout()
plt.savefig("Mean_Ho_He_by_marker.png", dpi=300)
plt.show()
# Allele diversity by marker
allele_data = pd.read_csv("allele_diversity_by_marker.csv")
plt.figure(figsize=(10, 6))
plt.bar(allele_data["Marker"], allele_data["Number_of_alleles"])
plt.xlabel("Microsatellite Marker")
plt.ylabel("Number of Different Alleles")
plt.title("Allele Diversity by Microsatellite Marker")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Allele_Diversity_by_marker.png", dpi=300)
plt.show()