import pandas as pd
import matplotlib.pyplot as plt
results = pd.read_csv("population_heterozygosity_results.csv")
location_ho = results.groupby("Location")["Ho"].mean()
plt.figure(figsize=(8, 5))
plt.bar(location_ho.index, location_ho.values)
plt.title("Average Observed Hetrozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Average Ho")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Average_observed_heterozygosity.png", dpi=300)
plt.show()
location_he = results.groupby("Location")["He"].mean()
plt.figure(figsize=(8, 5))
plt.bar(location_he.index, location_he.values)
plt.title("Average Expected Heterozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Average He")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Average_expected_heterozygosity.png", dpi=300)
plt.show()
comparison = results.groupby("Location")[["Ho", "He"]].mean()
comparison.plot(kind="bar", figsize=(8, 5))
plt.title("Observed vs Expected Heterozygosity by Location")
plt.xlabel("Location")
plt.ylabel("Heterozygosity")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("observed_vs_expected_heterozygosity.png", dpi=300)
plt.show()
marker_ho = results.groupby("Marker")["Ho"].mean()
plt.figure(figsize=(10, 5))
plt.bar(marker_ho.index, marker_ho.values)
plt.title("Average Observed Hetrozygosity by Marker")
plt.xlabel("Microsatellite Marker")
plt.ylabel("Average Ho")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("marker_heterozygosity.png", dpi=300)
plt.show()